Cart/urls.py
from django.urls import path


from .views import CartAddProductView, CartDetailView, CartRemoveView

app_name = 'Cart'
urlpatterns = [
    path('', CartDetailView.as_view(), name="cart_detail"),
    path('add/<int:product_id>/', CartAddProductView.as_view(), name="cart_add"),
    path('remove/<int:product_id>/', CartRemoveView.as_view(), name="cart_remove"),
]

Coupons/urls.py
from django.urls import path

from .views import CouponApplyView, remove_coupon

app_name = 'Coupons'
urlpatterns = [
    path('apply', CouponApplyView.as_view(), name="coupon_apply"),
    path('remove', remove_coupon, name="coupon_remove"),
]

OnlineShopProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include("Cart.urls", namespace='Cart')),
    path('coupons/', include('Coupons.urls', namespace='Coupons')),
    path('', include("Shop.urls", namespace='Shop')),
    path('', include("Orders.urls", namespace='Orders')),
]

Orders/urls.py
from django.urls import path

from .views import OrderCreateView, OrderCreatedView

app_name = 'Orders'
urlpatterns = [
    path('create/', OrderCreateView.as_view(), name="order_create"),
    path('created/<int:product_id>', OrderCreatedView.as_view(), name="order_created"),
]

Shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views
from .views import ProductDetailView, ProductListView, CategoryListView

app_name = 'Shop'
urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('<slug:category_slug>', CategoryListView.as_view(), name='category_list'),
    # path('', views.product_list, name='product_list'),
    # path('<slug:category_slug>', views.product_list, name='category_list'),
    path('product/<slug:slug>', ProductDetailView.as_view(), name='product_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cart/models.py
from django.db import models

# Create your models here.

Cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

Cart/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView, DeleteView, DetailView, TemplateView

from Shop.models import Product
from Shop.recommender import Recommender
from .cart import Cart
from .forms import CartAddProductForm
from Coupons.forms import CouponApplyForm
# Create your views here.


class CartAddProductView(FormView):
    form_class = CartAddProductForm
    template_name = "cart/cart_detail.html"
    success_url = reverse_lazy("Cart:cart_detail")
    product = None

    def form_valid(self, form):
        self.product = get_object_or_404(Product, id=self.kwargs['product_id'])
        cart = Cart(self.request)
        cart.add(product=self.product,
                 quantity=form.cleaned_data['quantity'],
                 override_quantity=form.cleaned_data['override'])
        return super(CartAddProductView, self).form_valid(form)


class CartRemoveView(View):

    def post(self, request, product_id):
        product = Product.objects.get(id=product_id)
        cart = Cart(request)
        cart.remove(product)
        return redirect('Cart:cart_detail')


class CartDetailView(TemplateView):
    template_name = 'cart/cart_detail.html'

    def get_context_data(self, **kwargs):
        cart = Cart(self.request)
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(initial={
                'quantity': item['quantity'],
                'override': True})
        r = Recommender()
        cart_products = [item['product'] for item in cart]
        recommended_products = r.suggest_products_for(cart_products, max_result=4)
        coupon_apply_form = CouponApplyForm()
        context = super().get_context_data()
        context['cart'] = cart
        context['coupon_apply_form'] = coupon_apply_form
        context['recommended_products'] = recommended_products
        return context

Cart/templates/cart/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Cart/templates/cart/cart_detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}
  <h1>Your shopping cart</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "Cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
{#                {{ item.quantity }}#}
            </td>
            <td>
              <form action="{% url "Cart:cart_remove" product.id %}" method="post">
                <input type="submit" value="Remove">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
          <tr class="subtotal">
              <td>Subtotal</td>
              <td colspan="4"></td>
              <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
          </tr>
          <tr>
              <td>
                  "{{ cart.coupon.code }}" coupon
                  ({{ cart.coupon.discount }}% off)
              </td>
              <td>
                  <form action="{% url "Coupons:coupon_remove" %}" method="post">
                      <input type="submit" value="Remove">
                      {% csrf_token %}
                  </form>
              </td>
              <td colspan="3"></td>
              <td class="num neg">
                  - ${{ cart.get_discount|floatformat:2 }}
              </td>
          </tr>
    {% endif %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">
            ${{ cart.get_total_price_after_discount|floatformat:2 }}
        </td>
      </tr>
    </tbody>
  </table>
    {% if recommended_products %}
        <div class="recommendations cart">
            <h3>"People who bought this also bought"</h3>
            {% for p in recommended_products %}
            <div class="item">
                <a href="{{ p.get_absolute_url }}">
                    <img src="{% if p.image %}{{ p.image.url }}{% else %}
                    {% static "img/no_image.png" %}{% endif %}">
                    </a>
                <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
            </div>
            {% endfor %}
        </div>
    {% endif %}
    <p class="text-right">Apply a coupon:</p>
    <form class="text-right" action="{% url "Coupons:coupon_apply" %}" method="post">
        {{ coupon_apply_form }}
        <input type="submit" value="Apply">
        {% csrf_token %}
    </form>
  <p class="text-right">
    <a href="{% url "Shop:product_list" %}" class="button
    light">Continue shopping</a>
    <a href="{% url "Orders:order_create" %}" class="button">
      Checkout
    </a>
  </p>
{% endblock %}